In [0]:
import keras
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
import numpy as np

Using TensorFlow backend.


In [0]:
#in convolution there will be a activation funct to remove -ve value cuz of feature detector(relu is used?)
mnist=keras.datasets.mnist
train_data,test_data=mnist.load_data()
train_images,train_labels=train_data
test_images,test_labels=test_data

11493376/11490434 [==============================] - 1s 0us/step


In [0]:
test_images.shape

(10000, 28, 28)

In [0]:
train_images=train_images.reshape(60000,28,28,1)
test_images=test_images.reshape(10000,28,28,1)

In [0]:
from keras.utils import to_categorical
train_labels=to_categorical(train_labels)
test_labels=to_categorical(test_labels)
train_labels[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [0]:
train_labels.shape

(60000, 10)

In [0]:
test_labels.shape

(10000, 10)

In [0]:
test_images


In [0]:
classifier=Sequential()

W0729 12:17:40.318704 139689430275968 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [0]:
#step 1:convolution layer in input shhape 3 is number of chnannels in colour change

classifier.add(Conv2D(32,(3,3),input_shape=(28,28,1),activation='relu'))



W0729 12:17:40.362679 139689430275968 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0729 12:17:40.376042 139689430275968 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [0]:
classifier.add(MaxPooling2D(pool_size=(2,2)))

W0729 12:17:40.417149 139689430275968 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.



In [0]:
classifier.add(Conv2D(64,(3,3),activation='relu'))
classifier.add(MaxPooling2D(pool_size=(2,2)))

In [0]:
classifier.add(Flatten())

In [0]:
#step 4 ann gonna use dense layers to implenent actual nueral layers
classifier.add(Dense(activation='relu',units=128))
classifier.add(Dense(activation='softmax',units=10))


In [0]:
classifier.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])#warning cuz old tf is used cuz keras wont work in lates

W0729 12:17:40.511291 139689430275968 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0729 12:17:40.541795 139689430275968 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [0]:
classifier.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 11, 11, 64)        18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1600)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               204928    
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1290      
Total para

In [0]:
train_images.shape

(60000, 28, 28, 1)

In [0]:
classifier.fit(train_images,train_labels,validation_data=(test_images,test_labels),epochs=5)

W0729 12:17:40.701115 139689430275968 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0729 12:17:40.760222 139689430275968 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 15s 244us/step - loss: 1.5035 - acc: 0.8817 - val_loss: 0.0574 - val_acc: 0.9825
Epoch 2/5
60000/60000 [==============================] - 8s 128us/step - loss: 0.0587 - acc: 0.9825 - val_loss: 0.0600 - val_acc: 0.9830
Epoch 3/5
60000/60000 [==============================] - 8s 128us/step - loss: 0.0456 - acc: 0.9862 - val_loss: 0.0556 - val_acc: 0.9834
Epoch 4/5
60000/60000 [==============================] - 8s 129us/step - loss: 0.0378 - acc: 0.9884 - val_loss: 0.0577 - val_acc: 0.9859
Epoch 5/5
60000/60000 [==============================] - 8s 129us/step - loss: 0.0325 - acc: 0.9899 - val_loss: 0.0592 - val_acc: 0.9853


In [0]:
test_labels[:4]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [0]:
i=classifier.predict(test_images[:4])

In [0]:
np.argmax(i,axis=1)

array([7, 2, 1, 0])

In [0]:
sample_index=1000
sample_img=test_images[sample_index]
sample_label=test_labels[sample_index]
prediction=classifier.predict(sample_img.reshape(1,28,28,1))
print("prediction",np.argmax(prediction))
print(np.argmax(sample_label))

prediction 9
9
