In [0]:
 #import libraries
import numpy as np
import matplotlib.pyplot as plt #used for plotting and visualization
import pandas as pd

In [0]:
#now import dataset
dataset = pd.read_csv('/content/preprocessing.csv')
#now we r going to store values of dependent and independent variables in x and y
#iloc is used to extract a subset of dataset
X = dataset.iloc[:,0:5].values#: indicates all rows
Y = dataset.iloc[:,5:6].values


In [0]:
X

array([[1, 'M', 19.0, 22000.0, 'JAPAN'],
       [2, 'M', 32.0, 15000.0, 'USA'],
       [3, 'F', 16.0, 130000.0, 'INDIA'],
       [4, 'M', 39.0, 54000.0, 'INDIA'],
       [5, 'M', nan, nan, 'USA'],
       [6, 'F', nan, 90000.0, 'JAPAN'],
       [7, 'F', 41.0, 67000.0, 'JAPAN'],
       [8, 'F', 22.0, nan, 'JAPAN'],
       [9, 'M', 31.0, nan, 'INDIA'],
       [10, 'M', 29.0, 13000.0, 'USA']], dtype=object)

In [0]:
Y

array([[1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1]])

In [0]:
from sklearn.preprocessing import Imputer
imputer=Imputer(missing_values='NaN' ,strategy='mean',axis=0)
imputer.fit(X[:,2:4])
X[:,2:4]=imputer.transform(X[:,2:4])

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [0]:
X

array([[1, 'M', 19.0, 22000.0, 'JAPAN'],
       [2, 'M', 32.0, 15000.0, 'USA'],
       [3, 'F', 16.0, 130000.0, 'INDIA'],
       [4, 'M', 39.0, 54000.0, 'INDIA'],
       [5, 'M', 28.625, 55857.142857142855, 'USA'],
       [6, 'F', 28.625, 90000.0, 'JAPAN'],
       [7, 'F', 41.0, 67000.0, 'JAPAN'],
       [8, 'F', 22.0, 55857.142857142855, 'JAPAN'],
       [9, 'M', 31.0, 55857.142857142855, 'INDIA'],
       [10, 'M', 29.0, 13000.0, 'USA']], dtype=object)

In [0]:
Y

array([[1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1]])

In [0]:
#label encoding=alphabetical order assignment (0,1,...)
#encoding the categorical data(with names as classes)
from sklearn.preprocessing import LabelEncoder
encoder_x=LabelEncoder()
X[:,1]=encoder_x.fit_transform(X[:,1])

In [0]:
X

array([[1, 1, 19.0, 22000.0, 'JAPAN'],
       [2, 1, 32.0, 15000.0, 'USA'],
       [3, 0, 16.0, 130000.0, 'INDIA'],
       [4, 1, 39.0, 54000.0, 'INDIA'],
       [5, 1, 28.625, 55857.142857142855, 'USA'],
       [6, 0, 28.625, 90000.0, 'JAPAN'],
       [7, 0, 41.0, 67000.0, 'JAPAN'],
       [8, 0, 22.0, 55857.142857142855, 'JAPAN'],
       [9, 1, 31.0, 55857.142857142855, 'INDIA'],
       [10, 1, 29.0, 13000.0, 'USA']], dtype=object)

In [0]:
#label encoding=alphabetical order assignment (0,1,...)
#encoding the categorical data(with names as classes)
from sklearn.preprocessing import LabelEncoder
encoder_x=LabelEncoder()
X[:,4]=encoder_x.fit_transform(X[:,4])

In [0]:
X

array([[1, 1, 19.0, 22000.0, 1],
       [2, 1, 32.0, 15000.0, 2],
       [3, 0, 16.0, 130000.0, 0],
       [4, 1, 39.0, 54000.0, 0],
       [5, 1, 28.625, 55857.142857142855, 2],
       [6, 0, 28.625, 90000.0, 1],
       [7, 0, 41.0, 67000.0, 1],
       [8, 0, 22.0, 55857.142857142855, 1],
       [9, 1, 31.0, 55857.142857142855, 0],
       [10, 1, 29.0, 13000.0, 2]], dtype=object)

In [0]:
#onehot encoding to removie weight ambiguity(spain has more weightage than others...)
from sklearn.preprocessing import OneHotEncoder
onehotencoder=OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:
X

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 2.20000000e+04, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.00000000e+00, 6.00000000e+00, 1.50000000e+04, 2.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        3.00000000e+00, 0.00000000e+00, 1.30000000e+05, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.00000000e+00, 7.00000000e+00, 5.40000000e+04, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.00000000e+00, 3.00000000e+00, 5.58571429e+04, 2.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        6.00000000e+00, 3.00000000e+00, 9.00000000e+04, 1.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        7.00000000e+00, 8.00000000e+00, 6.70000000e+04, 1.

In [0]:
Y

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [0]:
X.shape

(10, 8)

In [0]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=1/3,random_state=0)

In [0]:
x_train

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.00000000e+00, 6.00000000e+00, 1.50000000e+04, 2.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        7.00000000e+00, 8.00000000e+00, 6.70000000e+04, 1.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        8.00000000e+00, 2.00000000e+00, 5.58571429e+04, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.00000000e+00, 7.00000000e+00, 5.40000000e+04, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 2.20000000e+04, 1.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        6.00000000e+00, 3.00000000e+00, 9.00000000e+04, 1.00000000e+00]])

In [0]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [0]:
x_test

array([[ 1.        , -1.        ,  1.        ,  1.        , -0.65094455,
        -1.71105548,  3.09451544, -1.73205081],
       [-1.        ,  1.        , -1.        , -1.        ,  1.69245584,
         0.19011728,  0.20333   , -1.73205081],
       [-1.        ,  1.        , -1.        , -1.        ,  0.13018891,
        -0.57035183,  0.20333   ,  1.73205081],
       [-1.        ,  1.        , -1.        , -1.        ,  2.08302258,
        -0.19011728, -1.46787546,  1.73205081]])